### ISSUE TITLE
[BUG] Ticket closes and manual unmutes don't work when the specified privatebin is down

### ISSUE THREAD

**Issue by R3D4CTED** [Snaacky/chiya#123]
**Describe the bug**
When the privatebin is unavailable, tickets are unable to be closed, and manual unmutes are not possible (mute channel doesn't get deleted)

**To Reproduce**
1. Bring down the specified privatebin/enter an invalid URL for privatebin
2. Try to open a ticket and then `/close` it, or manually unmute a muted member
3. Command fails (defers indefinitely)

**Expected behavior**
For this error to be handled cleanly (display an error), or the chat logs be uploaded to an alternate bin, or added in the mute log/ticket log embed itself.

**Comment by Snaacky** [comment]
Need to test and see if this issue still affects the ticket system after the latest rewrite.

**Comment by Snaacky** [comment]
Plans to overhaul this system entirely so this issue is no longer needed.
