### ISSUE TITLE
Bug: endless reminder if you put 10s as duration

### ISSUE THREAD

**Issue by JohnTitor998** [Snaacky/chiya#256]
Problem:
i just tried to create a reminder in 10 seconds, lt started a countdown from 10 to 0, and then it started from 0 to... loop?

How to reproduce the error:
/reminder create duration: 10s message: test

**Comment by R3D4CTED** [comment]
Turns out, this was an issue with our production instance, a restart fixed it. The reminder event loop seemed to have gotten stuck for some reason, which needs to be debugged.
