### ISSUE TITLE
App directory reports not working

### ISSUE THREAD

**Issue by scourgeofgrozny** [Snaacky/chiya#257]
The option to report a specific message with Chiya through the app directory is currently greyed out for users. 

Current output:
![image](https://github.com/Snaacky/chiya/assets/124029849/3662eb8f-3a77-4d90-914e-fcf391f7d73c)
<br>
Expected output: 
![image](https://github.com/Snaacky/chiya/assets/124029849/90626321-e0f2-4799-8633-af7eab96f88e)

**Comment by R3D4CTED** [comment]
Make sure you click on the message context options.
